# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/garnet-miuicamera/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),garnet-miuicamera)

endif
